### ISSUE TITLE
Remove support for Webpack 1

### ISSUE THREAD

**Issue by srph** [sairion/buble-loader#15]
Buble doesn't transpile `import`/`export` statements, making Buble _impossible_ to work with Webpack 1. Moreover, Webpack 2 already does this.

Alternatively, we can add a warning for Webpack 1 users about this.

**Comment by kisenka** [comment]
+1 for warning

**Comment by sairion** [comment]
Good idea!

**Comment by srph** [comment]
I was supposed to make a PR to add a warning just now, but found it closed. Didn't find any related PRs either. Should I continue? :D

**Comment by sairion** [comment]
@srph Oh, sorry. Let me reopen :)

**Comment by nicko** [comment]
I've just created a PR for this loader to provide support for ES6 modules in Webpack 1: https://github.com/sairion/buble-loader/pull/22
