### ISSUE TITLE
Can't get object-assign package to work with buble-loader

### ISSUE THREAD

**Issue by Kunamatata** [sairion/buble-loader#26]
Hello,

I'm using webpack 2 with buble and buble loader. I have this code inside my `rules` array : 
```
{
	test: /.js$/,
	loaders: 'buble-loader',
	include: path.join(__dirname, 'client'),
	query: {
		objectAssign: 'object-assign'
	}
}
```

Unfortunetly, it seems like the polyfill just isn't working. I need to polyfill `Object.assign` for IE 11. 
The error I'm getting on whichever browser is the following `Uncaught ReferenceError: object is not defined`

**Comment by ssyz1988** [comment]
me too.
my webpack version is 2.2.0-rc,
and loader is buble-loader,
and i have installed object-assign package.

**Comment by oldskool73** [comment]
I used 

```
loaders: ['buble-loader?objectAssign=Object.assign','eslint-loader'],
```

with the `"object.assign": "^4.0.4",` package and 
```
// shim Object.assign for es5
require('object.assign/shim')();
```

at the start of my app code, seems to work.

**Comment by simon04** [comment]
The `objectAssign` option does not affect `Object.assign` usages in your code, but only affects how the object spread is transpiled.

**Comment by Kunamatata** [comment]
Thanks @simon04, I was assuming it was doing something different then it is supposed to.
