### ISSUE TITLE
peerinvalid Peer buble-loader@0.2.1 wants buble@0.7.0

### ISSUE THREAD

**Issue by roshansachan** [sairion/buble-loader#3]
Environment:
OS: Ubuntu 14.04 LTS
node - v0.10.25
npm - v1.3.10

Working on a laravel project and getting following error when installing npm.
![screenshot from 2016-06-27 20-23-28](https://cloud.githubusercontent.com/assets/4952904/16384743/c0c4513a-3ca7-11e6-985d-f0e621cb9370.png)

I tried doing npm install buble@^0.7.0 but it did not solve the issue.

**Comment by smayzes** [comment]
~~Getting this too. It's blocking my build.~~

Turns out my Node version was out of date. If you update Node, then it should be fixed.

**Comment by roshansachan** [comment]
Actually for me it worked by moving laravel-elixir from devDependencies to dependencies:
`{
 "private": true,
 "devDependencies": {
   "gulp": "^3.8.8"
 },
 "dependencies": {
   "laravel-elixir": "^4.0.0"
 }
}`
