### ISSUE TITLE
Webpack + Preact - Erro Transform Backticks ``

### ISSUE THREAD

**Issue by allexon** [sairion/buble-loader#34]
Hello, I am trying to learn and organize all the information in Reactive Development, I am not yet an expert on the subject, I am hoping to gather as much information as: Webpack, PWA, Service Works ..... among others, I want to be expecializar in developing applications Progressive Web Apps, I have made some advances, but still much is missing. For example I always found the bad Babel in your transpiler, very dirty the file ... So I discovered Buble, through this link -> https://nolanlawson.github.io/frontendday-2016/#1, I liked it a lot as is the result of the transpiler with Buble. Only that in my configuration is not working ... I use Webpack 3 + Preact + CSS Styled-Components (which is very good). I deleted my Babel configuration, which was working and I decided to adopt Buble. How do I set up:

1 - Webpack 3 with Buble?
2 - I tried to use this in Webpack ->
{test: /. js $ /, loaders: 'buble-loader', exclude: / node_modules /, include: Path.join (BIFAO_COMPONENTS),
                query: {objectAssign: 'Object.assign'}
              },
3 - As the styled-component uses `` backticks, it is giving this error:
Tagged template strings are not supported. Use `transforms: {templateString: false}` to skip transformation and disable this error, or `tra
nsforms: {dangerousTaggedTemplateString: true} `if you know what you're doing (45: 0)
 @ multi (webpack) -dev-server / client? http: // localhost: 9000 ./bifaosteakhouse/components/app.js

4 - Like where I include in the webpack this part:
buble ({jsx: 'h'})

**Comment by sairion** [comment]
Sorry, but I don't think this is good place to ask this question. (actually I have no idea for your issue)
