### ISSUE TITLE
Still accepting PRs?

### ISSUE THREAD

**Issue by sethlivingston** [sairion/buble-loader#37]
buble-loader has gotten pretty far behind buble, especially the browser targets and their supported features. Is @sairion still accepting PRs?

**Comment by sairion** [comment]
Sorry, I didn't notice people are still using this lib much. I don't get notifications from github directly. But if you need review for PR or there's any issue needs immediate attention, you can email me but I'll try to merge PRs as fast as I can (not taking more than a week)
