### ISSUE TITLE
TypeError: Cannot read property \'transforms\' of null\n    at Object.module.exports

### ISSUE THREAD

**Issue by shakaran** [sairion/buble-loader#39]
I am not sure if this is a bug on this project or related to laravel-mix or other, I gonna post here the issue, because I am lost finding how to resolve the problem:

```
# gulp default
[11:33:13] Using gulpfile /var/www/web/gulpfile.js
[11:33:13] Starting 'all'...
[11:33:13] Starting 'less'...
[11:33:25] Finished 'less' after 12 s
[11:33:25] Starting 'copy'...
[11:33:25] Finished 'copy' after 47 ms
[11:33:25] Starting 'copy'...
[11:33:25] Finished 'copy' after 145 ms
[11:33:25] Starting 'webpack'...
{ [Error: ./resources/assets/js/app.js
Module build failed: TypeError: Cannot read property 'transforms' of null
    at Object.module.exports (/var/www/web/node_modules/buble-loader/index.js:18:46)]
  message: './resources/assets/js/app.js\nModule build failed: TypeError: Cannot read property \'transforms\' of null\n    at Object.module.exports (/var/www/web/node_modules/buble-loader/index.js:18:46)',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }

```

As far I could see, I have this versions:

`./node_modules/laravel-elixir-webpack-official/package.json:34:    "buble-loader": "^0.2.2",`

`./package.json:16:    "buble-loader": "^0.5.0",`

**Comment by Elastic1** [comment]
I have the same problem too, when i raise the version of webpack 3 to 4

**Comment by roqstarco** [comment]
Anyone has a solution to fix this bug?

**Comment by nedt** [comment]
Same here. My quick fix is a default value for config in index.js:
```diff
 module.exports = function(source) {
+	const config = loaderUtils.getOptions(this) || {};
-	const config = loaderUtils.getOptions(this);
 	config.transforms = Object.assign({}, config.transforms || {}, { modules: false });
 	let output;
 	try {
```

But I got the feeling there's something else going on and this doesn't fix the underlying problem, only hiding it.

**Comment by shakaran** [comment]
I had to downgrade to webpack 3 and use bubble loader 0.4.1. This is a problem for lavarel elixir too since it has problems with webpack 4. I have clients waiting a solution depending of this bug

**Comment by TuguldurJ** [comment]
This is an ugly error to shown. I had to downgraded all my dependencies like webpack, webpack-dev-server. Please someone fix this issue. This would be very helpful. 

Thank you

**Comment by Elastic1** [comment]
```js
    // webpack.config.js
      {
        test: /\.js$/,
        exclude: /node_modules/, 
        loader: 'buble-loader', 
        options: {
          // you need to write something here
          // example
          objectAssign: 'Object.assign',
        }
      }
```

**Comment by j-jonas** [comment]
The fix can be found here:
https://github.com/sairion/buble-loader/commit/4cd22ef3184b5d52329bf0c8d596da4b38cb0630
Unfortunally the last version 0.5.0 is not up to date so u need to checkout the master version, to solve the problem.
Just run `npm install git+https://github.com/sairion/buble-loader.git\#master --save-dev`

**Comment by sairion** [comment]
sorry, forgot to publish. v0.5.1 is released : https://www.npmjs.com/package/buble-loader/v/0.5.1
