### ISSUE TITLE
Allow passing options to buble

### ISSUE THREAD

**Issue by analog-nico** [sairion/buble-loader#5]
I need to pass additional options to `buble.transform`. I patched the `buble-loader` code like this to make it work:

``` diff
    var transformed = buble.transform(source, {
        transforms: {
            modules: false
-       }
+       },
+           objectAssign: 'angular.extend'
    });
```

It would be great if I could somehow pass additional options through the webpack configuration to the buble-loader which are then added like shown above!

**Comment by kevinrenskers** [comment]
Yep, same with passing `target`.

**Comment by analog-nico** [comment]
Awesome, thanks for the new release!
